name: OWASP scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 2,5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: OWASP dependency scanning of Gradle build dependencies
        run: ./gradlew dependencyCheckAggregate

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-reports
          path: build/reports/dependency-check-report.html
